### PR TITLE
Landing page+dev

### PR DESCRIPTION
**Pull request by Teramino**
# Overview

- Every clickable button will take you to the product page according to the filter listed for that button.

- Search by category field at the top of the page will filter by category and/ trade option type.

- Each item row is filter by some category. The items shown is live data from that specific category.

# Updated Files

1. ### views.py

- index function
Query database for specific items based on category filter(Books, Recent Items, Popular Items).

- products functions
Fixed code so that when a category is selected is shows its been selected when submit button is pressed.
Also pushed trade options types from the backend so it can be viewed from the front end

2. ### products.html

- Displayed trade option types

3. ### index.html

- Added live data to the page according to filter.

- Every link is live and will filter according to link.

- Search my category bar is working properly. Search can happen either by category or trade option type of both.

# Testing

1. On products page
 

- Each filter is filtering and display data correctly

2. On Landing page

- Live data is shown correctly based on filter of that item row

- When clicking "View Category" for that row it takes you to the product page and its filtering correctly

### CODE REVIEW

**Comment by egomish** [comment]
- On the landing page, the buttons that used to say "Show Category" now say "View Recent Posts", "View Popular Posts", and "View Category" respectively. Given that we don't use the term "post" anywhere else in the UI, it would make more sense if the buttons said "View Recent Items", "View Popular Items", and "View Textbooks".
- The footer is much narrower than the width of the page. This appears to be a regression.
- There's a horizontal rule between the section "So, why Slug Trade?" and "Shop Textbooks", but not between any of the other sections. (This is also the case in the main branch, though.)
- In the "Shop Categories" section, there are only four categories, "Bikes", "Clothes", "Electronics", and "Textbooks". The following categories are not represented: "Household", "Other", "Movies", "Music", "Instruments", "Tickets", "Tools", "Toys", "Gaming", "Outdoors", "Office", "Furniture", "Appliances", "Fitness". Is this intentional?

**Comment by Sidney-** [comment]
1. I agree the buttons should be named to specify exactly what they are. 
2. Fixed the footer
3.I did this because its just a floating block of text whereas all of the other parts of the homepage are more like functioning sections. Its just to create a barrier to show that its a different area. If it looks bad i can remove it. It's just a matter of style really. 
4. I spoke with Kory about this earlier and he said he wants to do it. So maybe reach out to him about when it will be done. Technically if this isnt finished its not apart of sprint 1 so i look at this like bonus material

**Comment by Teramino** [comment]
- Forgot to mention the "Show Categories" section. Those are working and I'm in the works of adding the other categories to the landing page.

**Comment by egomish** [comment]
Changed the button text. (I tried "View Category" for all three, but I didn't think it looked good--I think the button text matching the section title gives creates cohesion for each section. Also, recent items and popular items are a way to sort, not a category.)

**Pull request merged**
