### PR TITLE
fixed profile page style

### PR DESCRIPTION
**Pull request by Sidney-**
The profile page was styled differently so i put it back to how it was before and also fixed the stretch issue on the background image when adding a wishlist item. Now the left div scrolls.

Testing
-Check that the background does not stretch when adding wishlist items

### CODE REVIEW

**Comment by AustinKellar** [comment]
Sidney and I discussed a change for this that will work for both of us but I haven't had the chance to push the change yet. Please wait on this pull request until I notify you of the change.

**Comment by AustinKellar** [comment]
I made the change that Sidney and I discussed. The panel does still have a separate scrolling bar but I think its usable since its situated to the left. I think it looks better now that the profile panel shows a little bit of the background picture around it, though I'm far from totally happy about it. I think the best course of action is to merge this 'compromise', but let me know what you think. I'm definitely still willing to iterate further on this if you have some ideas.

**Comment by egomish** [comment]
I don't see two scrollbars as viable UX-wise, and I don't think it's controversial to say that good user experience is more important than a consistent aesthetic.

What if we used a solid color on all the pages, instead of a background image? Not grey, but maybe on some kind of theme (like UCSC school colors--blue and yellow)?

**Comment by AustinKellar** [comment]
Sidney and I iterated a couple more time and ended with the profile page being separated into 2 sections. On the left, there is the basic information and on the right, the closet is displayed. In order to keep a consistent layout on the page, we added pagination to the closet items. 

How to test:
- Go to /profile and make sure that the page looks decent and also (more importantly) that it is usable.
- Add more than 6 items to your closet to make sure that pagination is working.
- Make sure the Edit Item link works

**Comment by egomish** [comment]
When I hover over the image or title of a closet item, the cursor changes into a pointing finger to indicate that the element is interactable even though it isn't. Is this machine-specific (I'm on Ubuntu + Firefox, Ubuntu + Chrome), or does it also happen on your machine?

**Comment by AustinKellar** [comment]
It isn't machine specific, that's a CSS rule that was put there intentionally when the items were directly clickable. It was an oversight not to remove it once they became un-clickable. Good find, I'll fix it in a minute and update the PR again

**Comment by egomish** [comment]
As discussed on Slack, the cursor behavior is intentional--the closet item image and title will route to the item detail page, which has not yet been implemented.

**Pull request merged**
